-- SQL Document: User Management and Authentication Hooks

-- This document defines custom types, tables for user profiles and roles,
-- and functions/triggers to integrate with Supabase authentication,
-- particularly handling new user sign-ups and custom access tokens.

-- ====================================================================
-- 1. Custom Types
-- Defines an ENUM type for different application roles a user can have.
-- ====================================================================
create type public.role as enum('user', 'member', 'admin', 'superadmin');

-- ====================================================================
-- 2. Tables
-- Defines the `user_roles` and `users` tables to manage application-specific
-- user data and their assigned roles.
-- ====================================================================

-- USER ROLES TABLE
-- Stores the application role for each user, linking to the auth.users table.
create table public.user_roles (
  id bigint generated by default as identity primary key, -- Unique identifier for the role entry
  user_id uuid references auth.users on delete cascade not null, -- Foreign key to auth.users table, cascading delete
  role public.role not null default 'user'::public.role, -- The assigned role, defaults to 'user'
  unique (user_id, role) -- Ensures a user cannot have the same role assigned multiple times
);

-- Enable Row Level Security (RLS) for the user_roles table.
-- RLS policies will control who can access or modify rows in this table.
alter table public.user_roles enable row level security;

comment on table public.user_roles is 'Application roles for each user.';

-- USER TABLE
-- Stores additional profile information for application users, linked to auth.users.
create table public.users (
    id uuid primary key references auth.users (id) on delete cascade, -- Primary key, also a foreign key to auth.users, cascading delete
    email text not null unique, -- User's email, must be unique
    username text, -- Optional username
    first_name text, -- User's first name
    last_name text, -- User's last name
    bio text, -- Short biography or description for the user
    created_at timestamp with time zone default now() not null, -- Timestamp of record creation
    updated_at timestamp with time zone default now() not null -- Timestamp of last update
);

-- Enable Row Level Security (RLS) for the users table.
alter table public.users enable row level security;

comment on table public.users is 'Application users'' profiles.';

-- ====================================================================
-- 3. Supabase Auth Hooks
-- Functions and policies related to integrating with Supabase authentication
-- for custom claims and new user handling.
-- ====================================================================

-- Custom Access Token Hook Function
-- This function is called by Supabase Auth to inject custom claims into a user's
-- JWT access token. Here, it adds the 'user_role' claim.
create or replace function public.custom_access_token_hook (event jsonb)
returns jsonb
language plpgsql
stable as $$
  declare
    claims jsonb;
    user_role public.role;
  begin
    -- Extract current claims from the event payload
    claims := event->'claims';

    -- Fetch the user role from the public.user_roles table
    -- based on the user_id provided in the event.
    select role into user_role
    from public.user_roles
    where user_id = (event->>'user_id')::uuid;

    -- If a role is found, set it as a 'user_role' claim.
    if user_role is not null then
      claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else
      -- If no role is found, set 'user_role' claim to null.
      claims := jsonb_set(claims, '{user_role}', 'null');
    end if;

    -- Update the 'claims' object in the original event payload
    -- before returning it.
    event := jsonb_set(event, '{claims}', claims);

    -- Return the modified event, which Supabase Auth will use to create the token.
    return event;
  end;
$$;

-- Grant usage on the public schema to `supabase_auth_admin` role.
grant usage on schema public to supabase_auth_admin;

-- Grant execution rights on the `custom_access_token_hook` function to `supabase_auth_admin`.
grant execute on function public.custom_access_token_hook to supabase_auth_admin;

-- Revoke execution rights from `authenticated`, `anon`, and `public` roles
-- to ensure only the auth system can call this sensitive function.
revoke execute on function public.custom_access_token_hook
from authenticated, anon, public;

-- Grant all privileges on the `public.user_roles` table to `supabase_auth_admin`.
grant all on table public.user_roles to supabase_auth_admin;

-- Revoke all privileges from `authenticated`, `anon`, and `public` roles on `public.user_roles`.
revoke all on table public.user_roles
from authenticated, anon, public;

-- RLS Policy for user_roles table
-- Allows `supabase_auth_admin` to read all user roles.
create policy "Allow auth admin to read user roles"
on public.user_roles
as permissive
for select
to supabase_auth_admin
using (true);

-- ====================================================================
-- 4. New User Signup Handler
-- Function and trigger to automatically manage public.users and public.user_roles
-- entries upon a new user signing up in auth.users.
-- ====================================================================

-- Function to handle new user creation
-- This function is triggered after a new user is inserted into `auth.users`.
-- It either updates an existing `public.users` entry (if matched by email)
-- or creates a new one, and assigns a default role.
create or replace function public.handle_new_user ()
returns trigger
language plpgsql
security definer -- Runs with the privileges of the function's owner (typically postgres)
as $$
DECLARE
    existing_user_id BIGINT; -- Variable to hold the ID of an existing user profile
BEGIN
    -- Check if a user profile with the new user's email already exists in `public.users`.
    SELECT id INTO existing_user_id
    FROM public.users
    WHERE email = NEW.email; -- NEW refers to the newly inserted row in auth.users

    IF existing_user_id IS NOT NULL THEN
        -- If an existing user profile is found (e.g., pre-created by an admin),
        -- update its ID to match the new `auth.users.id` and refresh `updated_at`.
        UPDATE public.users
        SET
            user_id = NEW.id,
            email = NEW.email, -- Update email just in case, though it should match if found.
            updated_at = now()
        WHERE id = existing_user_id;
    ELSE
        -- If no existing user profile, create a new one in `public.users`.
        INSERT INTO public.users (user_id, email, username)
        VALUES (
          NEW.id, -- Use the auth.users ID as the primary key for public.users
          NEW.email,
          -- Attempt to get a username from user metadata, otherwise generate one.
          coalesce(NEW.raw_user_meta_data->>'username', 'user-' ||SPLIT_PART(NEW.id::TEXT, '-', 5) )
        );

        -- Assign a default 'user' role to the newly created user.
        INSERT INTO public.user_roles(user_id, role) -- Note: Corrected to user_id instead of id.
        VALUES (NEW.id, 'user'::public.role);
    END IF;

    RETURN NEW; -- Return the new row from auth.users (required for AFTER triggers)
END;
$$;

-- Trigger to execute `handle_new_user` after a new user is created in `auth.users`.
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users -- Fires after an INSERT operation on auth.users
FOR EACH ROW -- For each row inserted
EXECUTE FUNCTION public.handle_new_user(); -- Execute the defined function
