-- SQL Document: User Management and Authentication Hooks

-- This document defines custom types, tables for user profiles and roles,
-- and functions/triggers to integrate with Supabase authentication,
-- particularly handling new user sign-ups and custom access tokens.

-- ====================================================================
-- 1. Custom Types
-- Defines an ENUM type for different application roles a user can have.
-- ====================================================================
create type public.role as enum('user', 'member', 'admin', 'superadmin');

-- ====================================================================
-- 2. Tables
-- Defines the `user_auth_roles` and `users` tables to manage application-specific
-- user data and their assigned roles.
-- ====================================================================

-- USER ROLES TABLE
-- Stores the application role for each user, linking to the auth.users table.
-- TODO: change this table to user_auth_roles to associate roles with auth.users
create table public.user_auth_roles (
  id bigint generated by default as identity primary key, -- Unique identifier for the role entry
  user_id uuid references auth.users on delete cascade not null, -- Foreign key to auth.users table, cascading delete
  role public.role not null default 'user'::public.role, -- The assigned role, defaults to 'user'
  unique (user_id, role) -- Ensures a user cannot have the same role assigned multiple times
);

-- Enable Row Level Security (RLS) for the user_auth_roles table.
-- RLS policies will control who can access or modify rows in this table.
alter table public.user_auth_roles enable row level security;

comment on table public.user_auth_roles is 'Application roles for each user.';

-- USER TABLE
-- Stores additional profile information for application users, linked to auth.users.
create table public.users (
    id uuid primary key references auth.users (id) on delete cascade, -- Primary key, also a foreign key to auth.users, cascading delete
    email text not null unique, -- User's email, must be unique
    username text, -- Optional username
    first_name text, -- User's first name
    last_name text, -- User's last name
    bio text, -- Short biography or description for the user
    profile_picture_url text, -- URL to the user's profile picture
    created_at timestamp with time zone default now() not null, -- Timestamp of record creation
    updated_at timestamp with time zone default now() not null -- Timestamp of last update
);

-- Enable Row Level Security (RLS) for the users table.
alter table public.users enable row level security;

comment on table public.users is 'Application users'' profiles.';


-- Armies TABLE
-- Stores additional profile information for application users, linked to auth.users.
create table public.armies (
    id bigint generated by default as identity primary key, 
    name TEXT,
    description TEXT,
    parent_army_id bigint references public.armies(id),
    created_at timestamp with time zone default now() not null, -- Timestamp of record creation
    updated_at timestamp with time zone default now() not null -- Timestamp of last update
);

-- Enable Row Level Security (RLS) for the users table.
alter table public.armies enable row level security;

comment on table public.armies is 'Application armies';

