---
title: Grimdark Database Schmema
description: This document describes the database schema for the Grimdark application.
---
classDiagram
    


    Class User {
        +int id
        +string username
        +stirng first_name
        +string last_name
        +string email
        +string profile_picture_url
        +DateTime created_at
        +DateTime updated_at
    }

